### ISSUE TITLE
POST /user  returns `Invalid Token` error

### ISSUE THREAD

**Issue by gedeondoescode** [gbrayhan/microservices-go#12]
I've just started to mess around with this template and I'm not fully experienced with how Golang works quite yet but I'm having trouble getting the /user endpoint to successfully create a new user due to a missing/invalid token within the authorization header. I'm not sure what the value could be or where it's located in the project (I assume it's in `config.json`) so I appreciate any help that I can get. 

Response with a random value: 
```json
{
    "error": "Invalid token"
}
```

Response with no value: 
```json
{
    "error": "Token not provided"
}
```

relevant Secure config values (all default values):
```json
{
    "Secure": {
	"JWTAccessSecure": "accesskeyyoumayneedtochangeit",
	"JWTRefreshSecure": "refreshkeyyoumayneedtochangeit",
	"JWTAccessTimeMinute": 10,
	"JWTRefreshTimeHour": 10
    },
}

**Comment by gbrayhan** [comment]
Hi @gedeondoescode you could disable the middleware temporary


// UserRoutes is a function that contains all routes of the user
func UserRoutes(router *gin.RouterGroup, controller *userController.Controller) {
	routerAuth := router.Group("/user")
	// routerAuth.Use(middlewares.AuthJWTMiddleware()) // JUST comment this line
	{ 
		routerAuth.POST("/", controller.NewUser)
		routerAuth.GET("/:id", controller.GetUsersByID)
		routerAuth.POST("/data", controller.GetDataUsers)
		routerAuth.PUT("/:id", controller.UpdateUser)
		routerAuth.DELETE("/:id", controller.DeleteUser)
	}
}

Dont forget revert this commented line once you create your new user with new credentials
