### ISSUE TITLE
Can you make the tutorials for build this repository?

### ISSUE THREAD

**Issue by lexuanquynh** [gbrayhan/microservices-go#3]
thanks for sharing your repo source code. if so can you share how to build your app?

**Comment by gbrayhan** [comment]
sorry for the delay, to compile it you only need to install docker and git on your computer and run the following command:

```bash
git clone https://github.com/gbrayhan/microservices-go
cd microservices-go
cp config.json.example config.json
docker-compose up  --build  -d
```

**Comment by lexuanquynh** [comment]
@gbrayhan  thank for you reply. I'm using Mac M1 silicon, so I think you need add this code into your compose file:
```json
mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
```

**Comment by gbrayhan** [comment]
Excellent!!, of course, if you like you can send a PR and I will gladly accept its buddy.
