### ISSUE TITLE
Incorrect docs.go after swag init 

### ISSUE THREAD

**Issue by Andree37** [gbrayhan/microservices-go#6]
**Describe the bug**
Whenever I do `swag init -g routes/ApplicationV1.go` the resulting docs.go is incorrect and doesn't look like the previous one.

**To Reproduce**
1. run `swag init -g routes/ApplicationV1.go`
2. verify docs.go
3. missing structs and most of the one that is there swag.Spec is unresolved.

**Expected behavior**
The docs.go should update correctly

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/33375224/203671996-8528d93b-6b26-4d40-b95a-6819af037dc0.png">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I just started using the Template and have ran `go get` to download all the mods. I have also installed swag/cmd but I am unaware of the correct version to use.

**Comment by Andree37** [comment]
Am I doing something wrong, or is there a reason why this is happening? :D

**Comment by gbrayhan** [comment]
you are doing the right thing @Andree37 , we are just working on solving those Swagger issues, the differences are just found because the new versions of swago add new directives.


In a week a new release of this boilerplate will be released with Go 1.19 version that will solve this issue.

Thank you for making this platform better day by day.

**Comment by gbrayhan** [comment]
In the new version of boilerplate these bugs were implemented and corrected, boilerplate uses all technologies using the latest version, in order to avoid security issues. So to answer your questions, the tools you should download are the latest version.
